name: melos
description: "A tool for managing Dart & Flutter repositories with multiple packages (monorepo). Supports automated versioning via Conventional Commits. Inspired by JavaScripts Lerna package."
version: 2.6.1-sunny
homepage: "https://github.com/invertase/melos"
publish_to: https://dart.cloudsmith.io/edspuzzles/edspuzzle-public

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ansi_styles: ^0.3.1
  args: ^2.0.0
  cli_util: ^0.3.0
  collection: ^1.14.12
  conventional_commit:
    hosted: https://dart.cloudsmith.io/edspuzzles/edspuzzle-public
    version: ^0.4.4
  dart_bom: ^1.9.0
  file: ^6.1.2
  equatable: ^2.0.5
  glob: ^2.0.2
  graphs: ^2.1.0
  http: ^0.13.1
  meta: ^1.1.8
  mustache_template: ^2.0.0
  path: ^1.8.2
  platform: ^3.1.0
  pool: ^1.4.0
  prompts: ^2.0.0
  pub_semver: ^2.1.3
  pub_updater: ^0.2.3
  pubspec: ^2.3.0
  string_scanner: ^1.1.1
  yaml: ^3.1.1
  yaml_edit: ^2.0.3

dev_dependencies:
  mockito: ^5.1.0
  test: ^1.21.1

executables:
  melos:
