name: conventional_commit
description: Parse a git commit message using the Conventional Commits specification.
version: 0.4.4-sunny
homepage: https://github.com/invertase/melos/tree/main/packages/conventional_commit
publish_to: https://dart.cloudsmith.io/edspuzzles/edspuzzle-public

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  collection: ^1.15.0
  test: ^1.17.5